### ISSUE TITLE
Home page not linked with the url

### ISSUE THREAD

**Issue by AdityaJ7** [Python-World/GitProfile#5] opened 2020-09-28 05:24 UTC
Home page not linked with the correct url
![Screenshot (637)](https://user-images.githubusercontent.com/42397096/94393522-d9665e00-0178-11eb-8075-eab78439d965.png)

Home button of this page

**Comment by AnkitJuyal009** [comment] 2020-09-28 14:37
Hey! @AdityaJ7 I didn't get the issue. Its just that if a user first time opens this site he would like to go for its username first so as to get his Github details. So how I can resolve is when user first opens it and clicks HomePage so it will open this dialog box
![image](https://user-images.githubusercontent.com/43692967/94446352-24f32900-01c6-11eb-9374-3907a5127403.png)

**Comment by AnkitJuyal009** [comment] 2020-09-28 14:38
Is it fine? Can I contribute to this and please assign to me if this is the problem that needs to be solve.

**Comment by AdityaJ7** [comment] 2020-09-29 03:24
The issue is there are two separate pages:- One where the result for the analysis is shown and other is the home page, once you see the results you cant go back to the home page by clicking the Home button as a wrong link is provided in href.

You just need to fix the URL that the home button points to.

The Url must be set to the main URL of the website, currently, it is set to #.

You can comment here if you still have doubts, Yesanyone can contribute to this project

**Comment by ampsteric** [comment] 2020-09-29 05:36
I would like to work on this issue as well. please assign in case the issue is not resolved.

**Closed as completed** 2021-09-16 06:16 UTC
Labels: good first issue, hacktoberfest, hacktoberfest2020
